### ISSUE TITLE
Warning Unsupported Engine

### ISSUE THREAD

**Issue by cjboco** [AsyncWeb/strapi-paypal#2]
In your docs, you state you are following the official Node.js release timelines.

But Node 16.x.x is in maintenance (as of this post) and 18.x.x is LTS.

My environment is Node 18.x.x. and I get an error message installing the plug-in:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'strapi-paypal@1.0.3',
npm WARN EBADENGINE   required: { node: '>=12.x.x <=16.x.x', npm: '>=6.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.14.1', npm: '9.3.1' }
npm WARN EBADENGINE }
```

Your docs state:

> Minimum environment requirements
> 
> Node.js >=14.x.x
> NPM >=6.x.x
> 
> We are following the [official Node.js releases timelines](https://nodejs.org/en/about/releases/).

You may want to also add a "Maximum environment requirements" section and perhaps even remove the "we are following" notation.

[Edit] Node v18.x is recommended for Strapi v4.3.9 and above

**Comment by nishekh-e-r** [comment]
@cjboco 
Thanks for reporting, we have updated the node engine versions.
