### ISSUE TITLE
Subscribe Button Not Working

### ISSUE THREAD

**Issue by mrtornado** [AsyncWeb/strapi-paypal#4]
So I've created a subscription for paypal, but the button does not want to work. For the Stripe plugin I managed to make it work by removing `class="css style"` from the button code `<button class="css style" type="button" class="SS_ProductCheckout" data-id="1" data-url="http://localhost:1337"> Subscribe </button>`
For this paypal plugin I changed also the `class="SS_ProductCheckout"` to `"PP_ProductCheckout"` because that's what the paypal JS function is asking for, and after I change that it's doing the fetch to `http://localhost:1337/strapi-paypal/getPaypalCheckout/1 `, but still it doesn't redirect me to the paypal page.  Here is a picture of it. 
<img width="602" alt="SCR-20230311-inrp" src="https://user-images.githubusercontent.com/9127007/224470806-0cafcd7e-7180-44fa-9943-ff1da10bf86b.png">

Any idea why ? 

here is also the error I get in the terminal where I run strapi: 

I've pasted it here: https://paste.ofcode.org/wXWaC6ghXCPa2cLccDbpch

 Sorry if it's a noob question my javascript is not that good :) and I was expecting the plugin to work out of the box. 

 I'm using `Strapi v4.7.1` and `Node v18.15.0` if that matters

**Comment by mrtornado** [comment]
oh and by the way `Config` > plugins.js didn't existed, so I created it and put the code in, also I've put the same code in `Config` > server.js , I don't know if that's ok or not :)

**Comment by nishekh-e-r** [comment]
@mrtornado Strapi recently upgraded the UI design system which includes several breaking changes. For example, Typescript was introduced, which is strongly typed. Another example is the upgraded Select component now has many more attributes. These breaking changes caused a few of the bugs that you all have been reporting. 

Good news! we have fixed those bugs. 

Please try out the latest version and let us know what you think. 
[https://www.npmjs.com/package/strapi-paypal](https://www.npmjs.com/package/strapi-paypal)
