### ISSUE TITLE
Optional live API keys

### ISSUE THREAD

**Issue by alvarolozano** [AsyncWeb/strapi-paypal#5]
I am testing this plugin locally, and when I set the configuration (settings screen), it requires me to enter my live PayPal client id/secret, which I don't have.
The expected behavior should be to make them required only if live mode (production) is enabled

**Comment by nishekh-e-r** [comment]
Strapi recently upgraded the UI design system which includes several breaking changes. For example, Typescript was introduced, which is strongly typed. Another example is the upgraded Select component now has many more attributes. These breaking changes caused a few of the bugs that you all have been reporting. 

Good news! we have fixed those bugs. and also we added all API keys in.env variables

Please try out the latest version and let us know what you think. 
[https://www.npmjs.com/package/strapi-paypal](https://www.npmjs.com/package/strapi-paypal)
