### ISSUE TITLE
Replace "stripe" with "paypal" and reference the original project

### ISSUE THREAD

**Issue by alvarolozano** [AsyncWeb/strapi-paypal#6]
It seems that this project is based on the Stripe plugin, so some translations say "stripe" instead of "paypal". Also, as it is based on another project, It should be mentioned in the project description

**Comment by nishekh-e-r** [comment]
@alvarolozano Strapi recently upgraded the UI design system which includes several breaking changes. For example, Typescript was introduced, which is strongly typed. Another example is the upgraded Select component now has many more attributes. These breaking changes caused a few of the bugs that you all have been reporting. 

Good news! we have fixed those bugs. 

Please try out the latest version and let us know what you think. 
[https://www.npmjs.com/package/strapi-paypal](https://www.npmjs.com/package/strapi-paypal)
