### ISSUE TITLE
Creating products or subscription can't push through

### ISSUE THREAD

**Issue by kevincaliboso** [AsyncWeb/strapi-paypal#7]
Description is a required field but I can't type on the field

**Comment by nishekh-e-r** [comment]
@kevincaliboso  Strapi recently upgraded the UI design system which includes several breaking changes. For example, Typescript was introduced, which is strongly typed. Another example is the upgraded Select component now has many more attributes. These breaking changes caused a few of the bugs that you all have been reporting. 

Good news! we have fixed those bugs. 

Please try out the latest version and let us know what you think. 
[https://www.npmjs.com/package/strapi-paypal](https://www.npmjs.com/package/strapi-paypal)
